[book]
authors = []
language = "zh"
src = "src"
title = "By welaken"
create-missing = true  

[output.html]
git-repository-url = "https://github.com/justlovemaki/CloudFlare-AI-Insight-Daily" # 替换成你的仓库地址
